apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grpc-encoder
  name: grpc-encoder
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: grpc-encoder
status:
  loadBalancer: {}
