apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cm-accounts
data:
  PORT: "3000"
  MONGO_DB: "argocdexample"
  MONGO_HOST: "mongo-argocdexample-mongodb.storage.svc"
  MONGO_PORT: "27017"
  MONGO_USER: "user"
  MONGO_PASSWORD: "pass"
  MONGO_SECURE: "true"
  JWT_SECRET: "MySecreT"
