apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fastify-passwords
  name: fastify-passwords
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: fastify-passwords
status:
  loadBalancer: {}
